<Project Sdk="Microsoft.NET.Sdk">

  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
	<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Camille.RiotGames" Version="3.0.0-nightly-2024-04-20-4d8da4ce47" />
    <PackageReference Include="Discord.Net" Version="3.13.0" />
    <PackageReference Include="eladaus.urldetector" Version="1.4.0" />
    <PackageReference Include="F23.StringSimilarity" Version="6.0.0" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.66.0.3205" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
    <PackageReference Include="MySql.Data" Version="8.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OpenAI" Version="1.10.0" />
    <PackageReference Include="Quartz" Version="3.8.0" />
    <PackageReference Include="TwitchLib" Version="3.5.3" />
    <PackageReference Include="TwitchLib.Api" Version="3.9.0" />
    <PackageReference Include="TwitchLib.Api.Core" Version="3.9.0" />
    <PackageReference Include="TwitchLib.Api.Core.Enums" Version="3.9.0" />
    <PackageReference Include="TwitchLib.Api.Core.Interfaces" Version="3.9.0" />
    <PackageReference Include="TwitchLib.Api.Helix" Version="3.9.0" />
    <PackageReference Include="TwitchLib.Communication" Version="1.0.6" />
    <PackageReference Include="TwitchLib.EventSub.Core" Version="2.5.2" />
    <PackageReference Include="TwitchLib.EventSub.Websockets" Version="0.5.0" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="IllPubSub">
			<HintPath>dlls\IllPubSub.dll</HintPath>
		</Reference>
		<Reference Include="RiotSharp">
			<HintPath>dlls\RiotSharp.dll</HintPath>
		</Reference>
	</ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="STRINGS\STRINGS.ko.resx">
      <LastGenOutput>STRINGS.ko.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="STRINGS\STRINGS.ja.resx">
      <LastGenOutput>STRINGS - Copy.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="STRINGS\STRINGS.fr.resx">
      <LastGenOutput>STRINGS - Copy.ru.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="STRINGS\STRINGS.resx">
      <LastGenOutput>STRINGS.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="STRINGS\STRINGS.ru.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>STRINGS.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="STRINGS\STRINGS.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>STRINGS.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
