//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillzBot.IllSTRINGS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class STRINGS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal STRINGS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkillzBot.STRINGS.STRINGS", typeof(STRINGS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been added as a channel moderator..
        /// </summary>
        internal static string AddModSuccess {
            get {
                return ResourceManager.GetString("AddModSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} received a VIP status..
        /// </summary>
        internal static string AddVIPSuccess {
            get {
                return ResourceManager.GetString("AddVIPSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, AntiBot protection lvl is set to {1}.
        /// </summary>
        internal static string AntiBotLvl {
            get {
                return ResourceManager.GetString("AntiBotLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} User {1} has been timed out for 1 hour and has also been blacklisted. The track is banned..
        /// </summary>
        internal static string BanUserForTrack_chatMessage {
            get {
                return ResourceManager.GetString("BanUserForTrack_chatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Command on cooldown ({1} s).
        /// </summary>
        internal static string BanUserForTrack_CoolDownmsg {
            get {
                return ResourceManager.GetString("BanUserForTrack_CoolDownmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Track from donation. The track has been blacklisted..
        /// </summary>
        internal static string BanUserForTrack_DonatedTrack {
            get {
                return ResourceManager.GetString("BanUserForTrack_DonatedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} donated {1} bits! PogChamp.
        /// </summary>
        internal static string BitsRecieved {
            get {
                return ResourceManager.GetString("BitsRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, {1} will be timed out for another {2} seconds. To summon him, you need {3} Channel Points. Check the rewards again, there is a reward for summoning {1} with the current price. The new reward will be available for a minute..
        /// </summary>
        internal static string CencelUval_ChatMessage {
            get {
                return ResourceManager.GetString("CencelUval_ChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0},  {1} is not timed out..
        /// </summary>
        internal static string CencelUval_NotInTimeOut {
            get {
                return ResourceManager.GetString("CencelUval_NotInTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward time is up.
        /// </summary>
        internal static string CencelUval_TimeOut {
            get {
                return ResourceManager.GetString("CencelUval_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} can&apos;t find {1}.
        /// </summary>
        internal static string CencelUval404 {
            get {
                return ResourceManager.GetString("CencelUval404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, ERROR: {1} Is stream online?.
        /// </summary>
        internal static string CreateClipERROR {
            get {
                return ResourceManager.GetString("CreateClipERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Clip have been created! {1}.
        /// </summary>
        internal static string CreateClipSuccess {
            get {
                return ResourceManager.GetString("CreateClipSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been removed from the channel moderators..
        /// </summary>
        internal static string DeleteModSuccess {
            get {
                return ResourceManager.GetString("DeleteModSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has lost his vip..
        /// </summary>
        internal static string DeleteVIPSuccess {
            get {
                return ResourceManager.GetString("DeleteVIPSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, can&apos;t find user named {1}.
        /// </summary>
        internal static string FindUser_ERROR404 {
            get {
                return ResourceManager.GetString("FindUser_ERROR404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} awards received. {1} Reward IDs saved in logs..
        /// </summary>
        internal static string GetAllReward_chatMessage {
            get {
                return ResourceManager.GetString("GetAllReward_chatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, no custom tracks.
        /// </summary>
        internal static string GetTrack404 {
            get {
                return ResourceManager.GetString("GetTrack404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, {1} https://youtu.be/{2} Track ordered by @{3}.
        /// </summary>
        internal static string GetTrackShow {
            get {
                return ResourceManager.GetString("GetTrackShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Gifted a sub for @{1} PogChamp (+600 Points).
        /// </summary>
        internal static string GiftedSubMessage {
            get {
                return ResourceManager.GetString("GiftedSubMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Bot commands⠀available at https://www.twitch.tv/bot_illskillz/about.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string InputERROR {
            get {
                return ResourceManager.GetString("InputERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot language has been set to Eng..
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat.
        /// </summary>
        internal static string loose {
            get {
                return ResourceManager.GetString("loose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} while summoner is in a match, he cannot be changed..
        /// </summary>
        internal static string LPInaMatch {
            get {
                return ResourceManager.GetString("LPInaMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Champ {1} ({2}/{3}/{4}), {5}, match {6}, {7}.
        /// </summary>
        internal static string MatchHistoryMessage {
            get {
                return ResourceManager.GetString("MatchHistoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended like a hero EZ.
        /// </summary>
        internal static string OnStreadDownHighLP {
            get {
                return ResourceManager.GetString("OnStreadDownHighLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended with shame PoroSad.
        /// </summary>
        internal static string OnStreadDownLowLP {
            get {
                return ResourceManager.GetString("OnStreadDownLowLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} is LIVE!.
        /// </summary>
        internal static string OnStreamUP {
            get {
                return ResourceManager.GetString("OnStreamUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator @{0} gifted life to @{1}.
        /// </summary>
        internal static string OnUnban {
            get {
                return ResourceManager.GetString("OnUnban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} https://euw.op.gg/summoners/euw/{1}.
        /// </summary>
        internal static string OpGGMessage {
            get {
                return ResourceManager.GetString("OpGGMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ban (spent 5 lives).
        /// </summary>
        internal static string PermaBanReason {
            get {
                return ResourceManager.GetString("PermaBanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} you have {1} points. Your place in the leaderboard: ({2}/{3}). You have {4} quiz points ({5}/{6}), in total you won {7} points ({8}/{9}).
        /// </summary>
        internal static string PointsMessage {
            get {
                return ResourceManager.GetString("PointsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREDICTION &quot;{0}&quot; IS LAUNCHED!.
        /// </summary>
        internal static string PredictionStarted {
            get {
                return ResourceManager.GetString("PredictionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIZ! {0}.
        /// </summary>
        internal static string QuizStart {
            get {
                return ResourceManager.GetString("QuizStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody gave the right answer..
        /// </summary>
        internal static string QuizTimeOut {
            get {
                return ResourceManager.GetString("QuizTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer: {0}! @{1} earned {2} point(s). You have {3} total points, all time {4} points. Points can be spent on ordering a track through the command !sr YouTube link.
        /// </summary>
        internal static string QuizWin {
            get {
                return ResourceManager.GetString("QuizWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role {0}.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Roulette on CoolDown {1}s remaining..
        /// </summary>
        internal static string RouletteCD {
            get {
                return ResourceManager.GetString("RouletteCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom! @{0} died..
        /// </summary>
        internal static string RouletteLoose {
            get {
                return ResourceManager.GetString("RouletteLoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom! @{0} died on the {1}th winstreak..
        /// </summary>
        internal static string RouletteLooseWs {
            get {
                return ResourceManager.GetString("RouletteLooseWs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roulette.
        /// </summary>
        internal static string RouletteTimeOut {
            get {
                return ResourceManager.GetString("RouletteTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Survived EZ.
        /// </summary>
        internal static string RouletteWin {
            get {
                return ResourceManager.GetString("RouletteWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} survived {1} times in a row!!! Your place in the leaderboard is {2} out of {3}! The probability of this winstreak is {4} PogChamp PogChamp PogChamp.
        /// </summary>
        internal static string RouletteWinStreak {
            get {
                return ResourceManager.GetString("RouletteWinStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Word too long to be sent to chat.
        /// </summary>
        internal static string SendMessageERROR {
            get {
                return ResourceManager.GetString("SendMessageERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, {1}, {2} {3}, {4} lp, WR {5}% {6} games played today, {7} wins / {8} losses. {9} LP earned.
        /// </summary>
        internal static string ShowLP {
            get {
                return ResourceManager.GetString("ShowLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Summoner {1} is being calibrated. {2} games played today, {3} wins / {4} losses. {5} LP earned.
        /// </summary>
        internal static string ShowLPCalibration {
            get {
                return ResourceManager.GetString("ShowLPCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0},  {1} PROMO TO {2}, {3}.
        /// </summary>
        internal static string ShowLPPromo {
            get {
                return ResourceManager.GetString("ShowLPPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please use the format: !CronEdit [taskName] [triggerName] [cronExpression].
        /// </summary>
        internal static string StartCronTaskERROR {
            get {
                return ResourceManager.GetString("StartCronTaskERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cron expression..
        /// </summary>
        internal static string StartCronTaskERROR2 {
            get {
                return ResourceManager.GetString("StartCronTaskERROR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job schedule updated..
        /// </summary>
        internal static string StartCronTaskSuccess {
            get {
                return ResourceManager.GetString("StartCronTaskSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Thank you for subscribing! It&apos;s your {1}th month with us! PogChamp +{2}.
        /// </summary>
        internal static string SubMessage {
            get {
                return ResourceManager.GetString("SubMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swearing.
        /// </summary>
        internal static string TimeOut1wReason {
            get {
                return ResourceManager.GetString("TimeOut1wReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18+ Image.
        /// </summary>
        internal static string TimeOutBadPic {
            get {
                return ResourceManager.GetString("TimeOutBadPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols in chat.
        /// </summary>
        internal static string TimeOutPic {
            get {
                return ResourceManager.GetString("TimeOutPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the streamer!.
        /// </summary>
        internal static string TimeOutReason_TimeOutBroadcaster {
            get {
                return ResourceManager.GetString("TimeOutReason_TimeOutBroadcaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNO reverse Card!.
        /// </summary>
        internal static string TimeOutReason_TimeOutRootUser {
            get {
                return ResourceManager.GetString("TimeOutReason_TimeOutRootUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeOut for subscriber.
        /// </summary>
        internal static string TimeOutReason_TimeOutSub {
            get {
                return ResourceManager.GetString("TimeOutReason_TimeOutSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeOut for unsubscriver.
        /// </summary>
        internal static string TimeOutReason_TimeOutUnsub {
            get {
                return ResourceManager.GetString("TimeOutReason_TimeOutUnsub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeOut for VIP.
        /// </summary>
        internal static string TimeOutReason_TimeOutVIP {
            get {
                return ResourceManager.GetString("TimeOutReason_TimeOutVIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        internal static string TimeOutReason_Track {
            get {
                return ResourceManager.GetString("TimeOutReason_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0},  {1} has been timed out for {2} s. It&apos;s his {3}-th timeout.
        /// </summary>
        internal static string TimeOutReward_chatMessage {
            get {
                return ResourceManager.GetString("TimeOutReward_chatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        internal static string TimeOutSpam {
            get {
                return ResourceManager.GetString("TimeOutSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 3 chat users: TOP 1 @{0}, {1} messages PogChamp TOP2 @{2}, {3} messages EZ TOP 3 @{4}, {5} messages BloodTrail.
        /// </summary>
        internal static string Top3Chat {
            get {
                return ResourceManager.GetString("Top3Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ 3 roulette players: TOP 1 @{0} win streak {1} {2} PogChamp TOP 2 @{3} win streak {4} {5} EZ TOP 3 @{6} win streak {7} {8} BloodTrail.
        /// </summary>
        internal static string Top3Roulette {
            get {
                return ResourceManager.GetString("Top3Roulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} An exception occurred in track order.
        /// </summary>
        internal static string Track_Esception {
            get {
                return ResourceManager.GetString("Track_Esception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Track {1} added to queue.
        /// </summary>
        internal static string Track200_Success {
            get {
                return ResourceManager.GetString("Track200_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Something went wrong. The track was not added to the queue.
        /// </summary>
        internal static string Track400_ERROR {
            get {
                return ResourceManager.GetString("Track400_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} There is nothing in the found videos to post..
        /// </summary>
        internal static string Track404 {
            get {
                return ResourceManager.GetString("Track404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, this track is not allowed..
        /// </summary>
        internal static string Track500_bannedTrack {
            get {
                return ResourceManager.GetString("Track500_bannedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} You don&apos;t have permission to add tracks.
        /// </summary>
        internal static string Track500_bannedUser {
            get {
                return ResourceManager.GetString("Track500_bannedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} 18+ videos is not allowed..
        /// </summary>
        internal static string Track510_Age {
            get {
                return ResourceManager.GetString("Track510_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Maximum video length is 6 minutes!.
        /// </summary>
        internal static string Track510_Duration {
            get {
                return ResourceManager.GetString("Track510_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} This video can only be viewed on YouTube.
        /// </summary>
        internal static string Track510_Embedded {
            get {
                return ResourceManager.GetString("Track510_Embedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} Views must be over 300k.
        /// </summary>
        internal static string Track510_ViewCount {
            get {
                return ResourceManager.GetString("Track510_ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} Chatted on {1} streams.
        /// </summary>
        internal static string TrackUserSuccess {
            get {
                return ResourceManager.GetString("TrackUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the nickname of the user who is in timeout. The bot will calculate the cost and write further actions to the chat. You will have a minute to complete them..
        /// </summary>
        internal static string UpdateRewardPromptOrig {
            get {
                return ResourceManager.GetString("UpdateRewardPromptOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untimeout {0}.
        /// </summary>
        internal static string UpdateRewardTitleNew {
            get {
                return ResourceManager.GetString("UpdateRewardTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untimeout user.
        /// </summary>
        internal static string UpdateRewardTitleOrig {
            get {
                return ResourceManager.GetString("UpdateRewardTitleOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, {1} sub/vip.
        /// </summary>
        internal static string Uval500_IsSub {
            get {
                return ResourceManager.GetString("Uval500_IsSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, {1} vip.
        /// </summary>
        internal static string Uval500_IsVIP {
            get {
                return ResourceManager.GetString("Uval500_IsVIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        internal static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
    }
}
